// Github Helper


import { Octokit } from "@octokit/rest";
import type { FileEntry } from "@/lib/types";




const ORG = "PawPawLabs" //process.env.GITHUB_ORGANIZATION;

function getOctokit() {
    return new Octokit({ auth: process.env.GITHUB_PAT });
}




export async function repoExists(repoName:string): Promise<boolean> {
    const octokit = getOctokit();
    try {
        await octokit.repos.get({ owner: ORG, repo: repoName });
        return true;
    } catch (err:any) {
        if (err.status === 404) return false;
        throw err;
    }
}




export async function createRepoAndPush(
    repoName: string,
    files: FileEntry[],
    commitMessage = "Initial commit from sandbox",
): Promise<string> {

    const octokit = getOctokit();

    // Create a repo (auto_init gives us a default branch with a commit)
    await octokit.repos.createInOrg({
        org: ORG,
        name: repoName,
        private: true,
        auto_init: true,
        description: "Generated by vibecoding agent",
    });

    // Push files into the new repo
    await pushFiles(octokit, repoName, files, commitMessage);

    return `${ORG}/${repoName}`;

}




export async function pushFiles(
    octokit: Octokit,
    repoName: string,
    files: FileEntry[],
    message: string,
) {




    // Get the latest SHA of the latest commit on the default branch
    const { data: ref } = await octokit.git.getRef({
        owner: ORG,
        repo: repoName,
        ref: "heads/main",
    });


    const latestCommitSha = ref.object.sha;




    // Get the tree SHA from that commit 
    const { data: commit  } = await octokit.git.getCommit({
        owner: ORG,
        repo: repoName,
        commit_sha: latestCommitSha,
    });


    const baseTreeSha = commit.tree.sha;




    // Create blovs for each file
    const blobs = await Promise.all(
        files.map((file) => 
            octokit.git.createBlob({
                owner: ORG,
                repo: repoName,
                content: Buffer.from(file.content).toString("base64"),
                encoding: "base64",
            })
        )
    );




    // Build the tree
    const tree = blobs.map(({ data }, index) => ({
        path: files[index].path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: data.sha,
    }));




    const { data: newTree } = await octokit.git.createTree({
        owner: ORG,
        repo: repoName,
        tree,
        base_tree: baseTreeSha,
    });




    // Create the commit
    const { data: newCommit } = await octokit.git.createCommit({
        owner: ORG,
        repo: repoName,
        message, 
        tree: newTree.sha,
        parents: [latestCommitSha],
    });




    // Update the branch ref to point to the new commit
    await octokit.git.updateRef({
        owner: ORG,
        repo: repoName,
        ref: "heads/main",
        sha: newCommit.sha,
    });




};




export async function readRepoFiles(
    repoName: string
): Promise<FileEntry[]> {
    

    const octokit = getOctokit();


    // Get the full tree recursively
    const { data: ref } = await octokit.git.getRef({
        owner: ORG,
        repo: repoName,
        ref: "heads/main",
    });




    const { data: tree } = await octokit.git.getTree({
        owner: ORG,
        repo: repoName,
        tree_sha: ref.object.sha,
        recursive: "true",
    });




    // Filter to only blobs
    const fileEntries = tree.tree.filter(
        (item) => item.type === "blob" && item.path
    );




    const files: FileEntry[] = await Promise.all(
        fileEntries.map(async (item) => {
            const { data } = await octokit.git.getBlob({
                owner: ORG,
                repo: repoName,
                file_sha: item.sha!,
            });
            return {
                path: item.path!,
                content: Buffer.from(data.content, "base64").toString("utf8")
            };
        })
    );




    return files;




};







